apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elk-operator.fullname" . }}-manager-config
  labels:
  {{- include "elk-operator.labels" . | nindent 4 }}
data:
  controller_manager_config.yaml: {{ .Values.managerConfig.controllerManagerConfigYaml
    | toYaml | indent 1 }}