apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "elk-operator.fullname" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "elk-operator.fullname" . }}-serving-cert
  labels:
  {{- include "elk-operator.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "elk-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-monitoring-snappcloud-io-v1alpha1-elkcluster
  failurePolicy: Fail
  name: velkcluster.kb.io
  rules:
  - apiGroups:
    - monitoring.snappcloud.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - elkclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "elk-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-monitoring-snappcloud-io-v1alpha1-elkuser
  failurePolicy: Fail
  name: velkuser.kb.io
  rules:
  - apiGroups:
    - monitoring.snappcloud.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - elkusers
  sideEffects: None