---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-monitoring-snappcload-io-v1alpha1-elkuser
  failurePolicy: Fail
  name: melkuser.kb.io
  rules:
  - apiGroups:
    - monitoring.snappcload.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - elkusers
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-monitoring-snappcload-io-v1alpha1-elkuser
  failurePolicy: Fail
  name: velkuser.kb.io
  rules:
  - apiGroups:
    - monitoring.snappcload.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - elkusers
  sideEffects: None
