---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-monitoring-snappcloud-io-v1alpha1-elkcluster
  failurePolicy: Fail
  name: melkcluster.kb.io
  rules:
  - apiGroups:
    - monitoring.snappcloud.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - elkclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-monitoring-snappcloud-io-v1alpha1-elkuser
  failurePolicy: Fail
  name: melkuser.kb.io
  rules:
  - apiGroups:
    - monitoring.snappcloud.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - elkusers
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-monitoring-snappcloud-io-v1alpha1-elkcluster
  failurePolicy: Fail
  name: velkcluster.kb.io
  rules:
  - apiGroups:
    - monitoring.snappcloud.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - elkclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-monitoring-snappcloud-io-v1alpha1-elkuser
  failurePolicy: Fail
  name: velkuser.kb.io
  rules:
  - apiGroups:
    - monitoring.snappcloud.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - elkusers
  sideEffects: None
