# permissions for end users to edit elks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elk-editor-role
rules:
- apiGroups:
  - monitoring.amirhnajafiz.github.com
  resources:
  - elks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.amirhnajafiz.github.com
  resources:
  - elks/status
  verbs:
  - get
