# permissions for end users to view elks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elk-viewer-role
rules:
- apiGroups:
  - monitoring.amirhnajafiz.github.com
  resources:
  - elks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.amirhnajafiz.github.com
  resources:
  - elks/status
  verbs:
  - get
