# permissions for end users to edit elkclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elkcluster-editor-role
rules:
- apiGroups:
  - monitoring.snappcloud.io
  resources:
  - elkclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.snappcloud.io
  resources:
  - elkclusters/status
  verbs:
  - get
