# permissions for end users to view elkclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elkcluster-viewer-role
rules:
- apiGroups:
  - monitoring.snappcloud.io
  resources:
  - elkclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.snappcloud.io
  resources:
  - elkclusters/status
  verbs:
  - get
