# permissions for end users to view elkusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elkuser-viewer-role
rules:
- apiGroups:
  - monitoring.snappcload.io
  resources:
  - elkusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.snappcload.io
  resources:
  - elkusers/status
  verbs:
  - get
