# permissions for end users to edit elkusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elkuser-editor-role
rules:
- apiGroups:
  - monitoring.snappcloud.io
  resources:
  - elkusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.snappcloud.io
  resources:
  - elkusers/status
  verbs:
  - get
