---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - monitoring.amirhnajafiz.github.com.github.com
  resources:
  - elks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.amirhnajafiz.github.com.github.com
  resources:
  - elks/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.amirhnajafiz.github.com.github.com
  resources:
  - elks/status
  verbs:
  - get
  - patch
  - update
